### PR TITLE
Add error to Validate if password is common

### PR DESCRIPTION
**Pull request by f0nkey**
Inspired by [how bad pattern locks are on phones](https://arstechnica.com/information-technology/2015/08/new-data-uncovers-the-surprising-predictability-of-android-lock-patterns/), I added some code to count continuous (or maybe contiguous) pattern lengths as 0.

If you swipe your finger across your keyboard, in any direction, along the red lines [in this image](https://i.imgur.com/RjBMAEW.png), it will be length 0.

Please let me know which changes you'd like to see and if these additions are appropriate. Disallowing patterns may count as one of those stupid rules. :smiley:

### CODE REVIEW

**Comment by lane-c-wagner** [comment]
Thanks for contributing! A couple of things:

* I don't want to entropy rules of this package to get too complex, that said I think this is a good idea. In order to "keep it simple" I would rather just keep a hard-coded list of "common" patterns that we can punish. Things like "qwerty" and "asdf".
* When we penalize a sequence we should still give it a length of 1 not 0
* I don't think this API makes sense. Looks like there is a new internal package that depends on some global variable being set? I would rather just enforce the "common" patterns I mentioned above with no added configurability

The take-aways here are:
* KISS
* This package will enforce the "best" entropy values, and won't expose configuration options

**Review by lane-c-wagner — CHANGES_REQUESTED** [review]
Thanks for contributing! A couple of things:

I don't want to entropy rules of this package to get too complex, that said I think this is a good idea. In order to "keep it simple" I would rather just keep a hard-coded list of "common" patterns that we can punish. Things like "qwerty" and "asdf".
When we penalize a sequence we should still give it a length of 1 not 0
I don't think this API makes sense. Looks like there is a new internal package that depends on some global variable being set? I would rather just enforce the "common" patterns I mentioned above with no added configurability
The take-aways here are:

KISS
This package will enforce the "best" entropy values, and won't expose configuration options

**Comment by f0nkey** [comment]
I considered removing common-password substrings, but that would penalize `battery` and `horse` from `correctbatteryhorsestaple`, which is considered a decent password!

Instead, I made it so `Validate` sees if the password matches 1:1 to a common one, and will tack on some text to the error, telling the user they should use an uncommon password.

Some common patterns are in the password list, such as variations of qwerty and asdf.

**Comment by f0nkey** [comment]
Need to embed most-common-passwords.txt into a go file instead of ioutil.Reading it, and change length to 1 if it matches a password before this is ready

**Comment by lane-c-wagner** [comment]
I applaud your efforts, but I feel we may be searching for a problem that doesn't exist. I don't love the idea of loading 10,000 strings into memory just by importing this package. Thanks for your efforts and I would love to see further contributions in the future. Maybe open an issue first so we can decide if it should be addressed before spending time coding!

**Pull request closed without merging**
